/**
 * Extensions of files that should be excluded from automatic test generation.
 * These are typically files generated by build_runner in Flutter (e.g., json_serializable, freezed).
 */
export const EXCLUDED_GENERATED_FILE_EXTENSIONS: string[] = [
    '.g.dart',
    '.freezed.dart'
];
