import * as vscode from 'vscode';

/**
 * Default extensions of files that should be excluded from automatic test generation.
 * These are typically files generated by build_runner in Flutter (e.g., json_serializable, freezed).
 */
const DEFAULT_EXCLUDED_EXTENSIONS: string[] = ['.g.dart', '.freezed.dart'];

/**
 * Gets the list of file extensions to exclude from automatic test generation.
 * Reads from user configuration or returns defaults if not configured.
 */
export function getExcludedFileExtensions(): string[] {
    const config = vscode.workspace.getConfiguration('flutterCoverage');
    const userExtensions = config.get<string[]>('excludedFileExtensions');

    // Return user configuration if exists, otherwise use defaults
    return userExtensions && userExtensions.length > 0 ? userExtensions : DEFAULT_EXCLUDED_EXTENSIONS;
}
