import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export interface TestResultData {
    name: string;
    success: boolean;
    coverage: {
        percentage: number;
        uncoveredLines: number[];
        file: string;
    } | null;
    sourceFile?: string;
}

export class UncoveredLinesExporter {
    public static async export(data: TestResultData[], defaultFileName: string, basePath?: string): Promise<void> {
        const content = this.generateMarkdown(data);

        let defaultUri: vscode.Uri;
        if (basePath) {
            defaultUri = vscode.Uri.file(path.join(basePath, defaultFileName + '_uncovered_report.md'));
        } else if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0) {
            defaultUri = vscode.Uri.joinPath(
                vscode.workspace.workspaceFolders[0].uri,
                defaultFileName + '_uncovered_report.md'
            );
        } else {
            defaultUri = vscode.Uri.file(defaultFileName + '_uncovered_report.md');
        }

        const uri = await vscode.window.showSaveDialog({
            defaultUri: defaultUri,
            filters: {
                Markdown: ['md']
            },
            saveLabel: 'Export Report'
        });

        if (uri) {
            try {
                fs.writeFileSync(uri.fsPath, content, 'utf8');
                vscode.window.showInformationMessage(`Report saved to ${path.basename(uri.fsPath)}`);
            } catch (error) {
                vscode.window.showErrorMessage(`Failed to save report: ${error}`);
            }
        }
    }

    private static generateMarkdown(data: TestResultData[]): string {
        const timestamp = new Date().toLocaleString();
        let md = `# Uncovered Lines Report\n\n`;
        md += `**Generated:** ${timestamp}\n\n`;

        for (const item of data) {
            // We want to show source file name if possible, else test name
            const fileName = item.sourceFile ? path.basename(item.sourceFile) : item.name;
            const percentage = item.coverage ? `${item.coverage.percentage}%` : 'N/A';
            const uncovered = item.coverage?.uncoveredLines?.length ? item.coverage.uncoveredLines.join(', ') : 'None';

            md += `**File**: ${fileName}\n\n`;
            md += `**Uncovered lines**: ${uncovered}\n\n`;
            md += `**Test Coverage Percentage**: ${percentage}\n\n`;
            md += `---\n\n`;
        }

        md += `*Generated by Flutter Coverage Tracker*`;
        return md;
    }
}
