import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export interface TestResultData {
    name: string;
    success: boolean;
    coverage: {
        percentage: number;
        uncoveredLines: number[];
        file: string;
    } | null;
    sourceFile?: string;
}

export class UncoveredLinesExporter {
    public static async export(data: TestResultData[], defaultFileName: string): Promise<void> {
        const content = this.generateMarkdown(data);

        const uri = await vscode.window.showSaveDialog({
            defaultUri: vscode.Uri.file(defaultFileName + '_uncovered_report.md'),
            filters: {
                'Markdown': ['md']
            },
            saveLabel: 'Export Report'
        });

        if (uri) {
            try {
                fs.writeFileSync(uri.fsPath, content, 'utf8');
                vscode.window.showInformationMessage(`Report saved to ${path.basename(uri.fsPath)}`);
            } catch (error) {
                vscode.window.showErrorMessage(`Failed to save report: ${error}`);
            }
        }
    }

    private static generateMarkdown(data: TestResultData[]): string {
        const timestamp = new Date().toLocaleString();
        let md = `# Uncovered Lines Report\n\n`;
        md += `**Generated:** ${timestamp}\n\n`;
        md += `| File | Coverage | Uncovered Lines |\n`;
        md += `|------|----------|----------------|\n`;

        for (const item of data) {
            // We want to show source file name if possible, else test name
            const fileName = item.sourceFile ? path.basename(item.sourceFile) : item.name;
            const percentage = item.coverage ? `${item.coverage.percentage}%` : 'N/A';
            const uncovered = item.coverage?.uncoveredLines?.length
                ? item.coverage.uncoveredLines.join(', ')
                : 'None';

            // Link to file if we have source path (local file link)
            // Note: Markdown local links might not work everywhere but fine for VS Code preview
            const nameDisplay = item.sourceFile
                ? `[${fileName}](${encodeURI(item.sourceFile)})`
                : fileName;

            md += `| ${fileName} | ${percentage} | ${uncovered} |\n`;
        }

        md += `\n---\n*Generated by Flutter Coverage Tracker*`;
        return md;
    }
}
